# Generated by Django 2.2.14 on 2020-07-31 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='booktype',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app02.BookType'),
        ),
    ]
